// Geo file generated by dolomites/tiziano
// --------------------------------------------------------
lc = 0.5;

// Points and Lines ---------------------------------------
Point(1)={0.0, 0.0, 0, lc};
Point(2)={2.0, 0.0, 0, lc};
Line(1)={1, 2};
Point(5)={2.0, 2.0, 0, lc};
Line(2)={2, 5};
Line(3)={5, 1};
Point(6)={0.0, 2.0, 0, lc};
Line(4)={5, 6};
Line(5)={6, 1};
Point(3)={4.0, 0.0, 0, lc};
Line(6)={2, 3};
Point(4)={4.0, 2.0, 0, lc};
Line(7)={3, 4};
Line(8)={4, 5};
Point(7)={5.0, 0.0, 0, lc};
Point(8)={7.0, 0.0, 0, lc};
Line(9)={7, 8};
Point(9)={7.0, 2.0, 0, lc};
Line(10)={8, 9};
Point(10)={5.0, 2.0, 0, lc};
Line(11)={9, 10};
Line(12)={10, 7};

// Curve Loops --------------------------------------------
 
Curve Loop(1)={1, 2, 3};

Curve Loop(2)={-3, 5, 4};

Curve Loop(3)={7, 8, -2, 6};

Curve Loop(4)={11, 12, 9, 10};

// Plane Surfaces -----------------------------------------
Plane Surface(1)={1};
Plane Surface(2)={2};
Plane Surface(3)={3};
Plane Surface(4)={4};

// Physical Surfaces --------------------------------------
Physical Surface(10)={1, 2, 4};
Physical Surface(30)={3};

// Physical Lines -----------------------------------------
Physical Line(5)={1, 4, 5, 6, 8};
Physical Line(8)={3};
Physical Line(2)={7};
Physical Line(4)={9, 11};
Physical Line(3)={12};
