// Geo file generated by dolomites/tiziano
// --------------------------------------------------------
lc = 0.3;

// Points and Lines ---------------------------------------
Point(11)={0.0, -1.0, 0, lc};
Point(5)={0.0, 0.0, 0, lc};
Line(1)={11, 5};
Point(1)={-3.0, -3.0, 0, lc};
Line(2)={5, 1};
Point(2)={3.0, -3.0, 0, lc};
Line(3)={1, 2};
Point(8)={-1.0, 0.0, 0, lc};
Line(4)={5, 8};
Point(4)={-3.0, 3.0, 0, lc};
Line(5)={4, 1};
Point(7)={-1.0, 1.0, 0, lc};
Point(6)={0.0, 1.0, 0, lc};
Line(6)={7, 6};
Line(7)={8, 7};
Point(9)={1.0, 0.0, 0, lc};
Point(10)={1.0, -1.0, 0, lc};
Line(8)={9, 10};
Line(9)={10, 11};
Point(12)={2.0, 2.0, 0, lc};
Line(10)={12, 5};
Line(11)={5, 9};
Point(3)={3.0, 3.0, 0, lc};
Line(12)={3, 4};
Line(13)={6, 5};
Line(14)={2, 3};

// Curve Loops --------------------------------------------
 
Curve Loop(1)={-7, -6, -13, -2, 5, 12, 14, 3, 2, -4};

Curve Loop(2)={-10, -11, -8, -9, -1, 10};

// Plane Surfaces -----------------------------------------
Plane Surface(1)={1, 2};

// Physical Surfaces --------------------------------------
Physical Surface(8)={1};

// Physical Lines -----------------------------------------
Physical Line(4)={1, 4, 6, 7, 8, 9, 11, 13};
Physical Line(5)={2};
Physical Line(2)={3, 5, 12, 14};
Physical Line(7)={10};
