// Geo file generated by dolomites/tiziano
// --------------------------------------------------------
lc = 0.2;

// Points and Lines ---------------------------------------
Point(26)={-1.0, -2.0, 0, lc};
Point(1)={0.0, -1.0, 0, lc};
Line(1)={26, 1};
Point(15)={-2.0, -1.0, 0, lc};
Point(17)={-3.0, 0.0, 0, lc};
Line(2)={15, 17};
Point(18)={-4.0, -1.0, 0, lc};
Line(3)={17, 18};
Point(24)={0.0, -3.0, 0, lc};
Line(4)={24, 26};
Point(25)={1.0, -2.0, 0, lc};
Line(5)={25, 24};
Line(6)={25, 1};
Point(8)={-8.0, 0.0, 0, lc};
Point(4)={0.0, -6.0, 0, lc};
Line(7)={8, 4};
Point(7)={-1.0, 0.0, 0, lc};
Line(8)={1, 7};
Line(9)={7, 15};
Point(20)={-5.0, 0.0, 0, lc};
Point(19)={-4.0, 1.0, 0, lc};
Line(10)={20, 19};
Line(11)={18, 20};
Point(6)={0.0, 6.0, 0, lc};
Line(12)={6, 8};
Point(16)={-2.0, 1.0, 0, lc};
Line(13)={7, 16};
Line(14)={16, 17};
Point(3)={0.0, 1.0, 0, lc};
Line(15)={7, 3};
Point(23)={-1.0, 2.0, 0, lc};
Line(16)={3, 23};
Line(17)={19, 17};
Point(9)={2.0, -1.0, 0, lc};
Point(2)={1.0, 0.0, 0, lc};
Line(18)={9, 2};
Point(10)={3.0, 0.0, 0, lc};
Line(19)={9, 10};
Point(12)={4.0, -1.0, 0, lc};
Line(20)={12, 10};
Point(13)={5.0, 0.0, 0, lc};
Line(21)={13, 12};
Point(11)={2.0, 1.0, 0, lc};
Line(22)={10, 11};
Line(23)={11, 2};
Point(22)={0.0, 3.0, 0, lc};
Line(24)={22, 23};
Point(21)={1.0, 2.0, 0, lc};
Line(25)={3, 21};
Line(26)={21, 22};
Line(27)={6, 22};
Point(14)={4.0, 1.0, 0, lc};
Line(28)={10, 14};
Line(29)={3, 2};
Point(5)={8.0, 0.0, 0, lc};
Line(30)={5, 6};
Line(31)={14, 13};
Line(32)={4, 5};
Line(33)={2, 1};

// Curve Loops --------------------------------------------
 
Curve Loop(1)={-1, 6, -5, -4};

Curve Loop(2)={-2, 14, 13, -9};

Curve Loop(3)={22, 23, -18, 19};

Curve Loop(4)={25, 26, 24, -16};

Curve Loop(5)={-33, -8, -15, -29};

Curve Loop(6)={32, 30, 27, -27, 12, 7};

Curve Loop(7)={-11, -10, -17, -3};

Curve Loop(8)={-20, -28, -31, -21};

// Plane Surfaces -----------------------------------------
Plane Surface(1)={1};
Plane Surface(2)={2};
Plane Surface(3)={3};
Plane Surface(4)={4};
Plane Surface(5)={6, 2, 3, 4, 5, 1, 7, 8};

// Physical Surfaces --------------------------------------
Physical Surface(8)={5};
Physical Surface(10)={1, 2, 3, 4};

// Physical Lines -----------------------------------------
Physical Line(7)={7, 12, 30, 32};
Physical Line(5)={27};

// Mesh -----------------------------------------------
Mesh 2;
Mesh.MshFileVersion = 2.2;
Save "test_geo_1.msh";
