// Geo file generated by dolomites/tiziano
// --------------------------------------------------------
lc = 0.3;

// Points and Lines ---------------------------------------
Point(4)={-3.0, 3.0, 0, lc};
Point(1)={-3.0, -3.0, 0, lc};
Line(1)={4, 1};
Point(5)={-1.0, 0.0, 0, lc};
Line(2)={1, 5};
Point(2)={3.0, -3.0, 0, lc};
Point(3)={3.0, 3.0, 0, lc};
Line(3)={2, 3};
Line(4)={1, 2};
Line(5)={3, 4};

// Curve Loops --------------------------------------------
 
Curve Loop(1)={5, 1, 2, -2, 4, 3};

// Plane Surfaces -----------------------------------------
Plane Surface(1)={1};

// Physical Surfaces --------------------------------------
Physical Surface(8)={1};

// Physical Lines -----------------------------------------
Physical Line(2)={1, 3, 4, 5};
Physical Line(5)={2};
